language: csharp
script:
    - xbuild /p:Configuration=Release vMenu.sln
notifications:
  webhooks:
    urls:
      - https://vespura.com/travis-ci.php
branches:
    except:
        - development
before_deploy:
    - cd /home/travis/build/TomGrobbe/build/ && rm *.pdb
    - cp ../vMenu/*.md ./
    - wget https://vespura.com/vmenu/__resource.lua
    - zip -r vMenu-$TRAVIS_TAG.zip *
deploy:
    provider: releases
    api_key: $GITHUB_API_KEY
    file: "/home/travis/build/TomGrobbe/build/vMenu-$TRAVIS_TAG.zip"
    skip_cleanup: true
    prerelease: false
    draft: true
    tag_name: $TRAVIS_TAG
    target_commitish: $TRAVIS_COMMIT
    name: "[Release] vMenu $TRAVIS_TAG"
    on:
        tags: true
